# This file was generated by GoReleaser. DO NOT EDIT.
cask "lyrics" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "6fc6cdb9563905bf693e4ee2455f87bc3abf0d4871df04f4e06211ad4df6bc1f"
      url "https://github.com/index-null/cmus-lyric/releases/download/v#{version}/cmus-lyric_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "96ac3b5131d76a8fecc94c165e6cc56c95e86028925bd0bc77678180fd9b89eb"
      url "https://github.com/index-null/cmus-lyric/releases/download/v#{version}/cmus-lyric_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "572b8f79b28bdb3100a4dc7c02a1863b7da06752681ec87baa0a11ec1bcfb602"
      url "https://github.com/index-null/cmus-lyric/releases/download/v#{version}/cmus-lyric_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "15d2244d9843a8d4ae7b3c2c084bb82a4ea0bf70db83963f65261bc02bf50fc2"
      url "https://github.com/index-null/cmus-lyric/releases/download/v#{version}/cmus-lyric_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lyrics"
  desc "Terminal-based synced lyrics viewer for cmus"
  homepage "https://github.com/index-null/cmus-lyric"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lyrics"

  # No zap stanza required

  caveats <<~EOS
    Requires cmus to be running. Start cmus first, then run 'lyrics'.
  EOS
end
