# This file was generated by GoReleaser. DO NOT EDIT.
cask "lyrics" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "91a05badc9048753fe03725749dab4861138905632c302f3e53d68816784991d"
      url "https://github.com/index-null/cmus-lyric/releases/download/v#{version}/cmus-lyric_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "15845af085b8ba669176cfc571b85f5fdf6750c12b1189cde543a4c383c7bf7a"
      url "https://github.com/index-null/cmus-lyric/releases/download/v#{version}/cmus-lyric_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "07d0f0e26a7a548426a44dd2e78ad1b80b88eb446625b69586c2d176e0fb1083"
      url "https://github.com/index-null/cmus-lyric/releases/download/v#{version}/cmus-lyric_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b884b75e3f9957cbed51e651ead6cab93c469fab68f277d129d8039a6a0c00ba"
      url "https://github.com/index-null/cmus-lyric/releases/download/v#{version}/cmus-lyric_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lyrics"
  desc "Terminal-based synced lyrics viewer for cmus"
  homepage "https://github.com/index-null/cmus-lyric"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lyrics"

  # No zap stanza required

  caveats <<~EOS
    Requires cmus to be running. Start cmus first, then run 'lyrics'.
  EOS
end
