# This file was generated by GoReleaser. DO NOT EDIT.
cask "lyrics" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "1706927a963d5ff7c7f8c9fcb0703fa81213585c998be43349aeae4c07047f68"
      url "https://github.com/index-null/cmus-lyric/releases/download/v#{version}/cmus-lyric_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c9a9c5cb2607c3d612c41aec1696ab469a8f8a275958133a80ae694ff15b50e0"
      url "https://github.com/index-null/cmus-lyric/releases/download/v#{version}/cmus-lyric_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bfd020a7576b9f1d554224f9c89d7da3393da33eb2137b170c16b9cbdfaa2017"
      url "https://github.com/index-null/cmus-lyric/releases/download/v#{version}/cmus-lyric_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c18174e266edab4e6c3fa5dce327da3d0ea2b60d6d833e82074a08e53297c70"
      url "https://github.com/index-null/cmus-lyric/releases/download/v#{version}/cmus-lyric_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lyrics"
  desc "Terminal-based synced lyrics viewer for cmus"
  homepage "https://github.com/index-null/cmus-lyric"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lyrics"

  # No zap stanza required

  caveats <<~EOS
    Requires cmus to be running. Start cmus first, then run 'lyrics'.
  EOS
end
